---
title: "Table 2 - continuous results"
output: pdf_document
date: "2023-05-10"
---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r , echo = FALSE}

# load libraries
library(dplyr)
library(foreign)
library(huxtable)
library(utils)
library(estimatr)
library(broom)

# define input, output
INPUT = paste0("C:/users/soere/Documents/migration_moldova", "/01_generate_data/OUTPUT/")


# Load dataset
load(paste0(INPUT, "community_data.rda"))


# Define global variables
controls <- c("pop_1500_3000", "pop_3000_9999", "district_capital", "distance_capital", "dist_bc", "chisinau_balti", "pop_all_0_14_sh", "pop_all_15_34_sh", "pop_all_65_99_sh", "pop_highedu_sh", "pop_lowedu_sh", "ratio_high_low_edu", "eth_rus_sh", "eth_rus_sh2", "eth_ukr_sh", "eth_ukr_sh2", "eth_gag_sh", "eth_gag_sh2", "eth_bul_sh", "eth_bul_sh2", "eth_fract")
controls2 <- c("pop_1500_3000", "pop_3000_9999", "district_capital", "distance_capital", "dist_bc", "chisinau_balti", "pop_all_0_14_sh", "pop_all_15_34_sh", "pop_all_65_99_sh", "pop_highedu_sh", "pop_lowedu_sh", "ratio_high_low_edu", "eth_rus_sh", "eth_ukr_sh", "eth_gag_sh", "eth_bul_sh", "eth_fract")
lights <- "lights92_99"
pre_treatment1998 <- c("comvot98", "pdmvot98", "dcvot98", "pdfvot98", "turnout98")
pre_treatment1994 <- c("agrarvot94", "socialistvot94", "pibvot94", "apcdfvot94")
migrant_characteristics <- c("sh_mig_all_15_34", "sh_mig_all_fem", "sh_mig_all_high")





table_2 <- function(comvotyear){
  
  model1 <- paste(comvotyear, " ~  prev_mig_west + prev_mig_east +", 
                  paste(controls, collapse = "+"), "+",
                  paste(pre_treatment1994, collapse = "+"), "+", 
                  paste(pre_treatment1998, collapse = "+"), "+",
                  paste(lights),
                  "+ as.factor(cod_rai)")
  model1 <- lm_robust(as.formula(model1), data = community_data, clusters = cod_rai, se_type = "stata")

}


table2 <- huxreg("2001" = table_2("comvot01"),
                 "2005" = table_2("comvot05"),
                 "April \n 2009" = table_2("comvot09apr"),
                 "July \n 2009" = table_2("comvot09jul"),
                 "2010" = table_2("comvot10"),
                 "2014" = table_2("comvot14nov"),
                 "2021" = table_2("comvot21jul"),
                 
                 coefs = c("Prevalence of emigration to the West (percent)" = "prev_mig_west",
                           "Prevalence of emigration to the East (percent)" = "prev_mig_east"),
                 
                 stars = NULL,
                 align = "r",
                 error_pos = "same", 
                 number_format = 2) %>%
  
  ## for subcaption
  insert_row("", "Share of Communist votes in parliamentary elections \n (percent)", "", "", "", "", "", "", after = 0) %>%
  set_caption("Migration Patterns and Communist Votes over Time, 2001–2021") %>%
  set_align(everywhere, everywhere, "center") %>% 

  merge_cells(1, 2:8) %>%
  set_bottom_border(1, 2:8) %>%
  set_bottom_border(2, 1:8) 
  
  
table2 <- huxtable::add_footnote(table2, "Notes: The table reports OLS estimates for 848 Moldovan communities. The dependent variables are the vote shares of the Communist Party in the parliamentary elections between 2001 and 2010 at the community level (in percent) (columns 1–5) and a binary indicator for whether a Communist mayor was elected in the municipal elections of 1999, 2003, and 2007 (columns 6–8). The full set of controls includes community-level variables capturing population size, age structure, ethnic composition, skill level, and distribution of the population, a dummy for district capitals and the cities of Chisinau and Balti, the distance to the district capital and the next Romanian border crossing, as well as premigration election results and night-light intensity. Standard errors, clustered at the district level, are in parentheses.")

col_width(table2) <- c(0.3, 0.09, 0.09, 0.09, 0.09, 0.09, 0.08, 0.09)
width(table2) <- 1
wrap(table2) <- TRUE
font_size(table2) <- 8

position(table2) <- "left"

table2
```


