---
title: "Replication - Tables"
output: pdf_document
date: "2023-05-10"
---

# Election results from Parliament election (Table 1)


```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

# load libraries
pacman::p_load(dplyr, 
               foreign, 
               lmtest, 
               sandwich, 
               estimatr, 
               texreg, 
               latexpdf, 
               huxtable,
               tinytex,
               stargazer)

# define input, output
setwd("C:/users/soere/Documents/migration_moldova")
INPUT = paste0("C:/Users/soere/Documents/migration_moldova/01_generate_data/OUTPUT/")
OUTPUT = paste0("C:/Users/soere/Documents/migration_moldova/03_renew_paper/OUTPUT/") 


# Load dataset
load(paste0(INPUT, "community_data.rda"))


# Define global variables
controls <- c("pop_1500_3000", "pop_3000_9999", "district_capital", "distance_capital", "dist_bc", "chisinau_balti", "pop_all_0_14_sh", "pop_all_15_34_sh", "pop_all_65_99_sh", "pop_highedu_sh", "pop_lowedu_sh", "ratio_high_low_edu", "eth_rus_sh", "eth_rus_sh2", "eth_ukr_sh", "eth_ukr_sh2", "eth_gag_sh", "eth_gag_sh2", "eth_bul_sh", "eth_bul_sh2", "eth_fract")
controls2 <- c("pop_1500_3000", "pop_3000_9999", "district_capital", "distance_capital", "dist_bc", "chisinau_balti", "pop_all_0_14_sh", "pop_all_15_34_sh", "pop_all_65_99_sh", "pop_highedu_sh", "pop_lowedu_sh", "ratio_high_low_edu", "eth_rus_sh", "eth_ukr_sh", "eth_gag_sh", "eth_bul_sh", "eth_fract")
lights <- "lights92_99"
pre_treatment1998 <- c("comvot98", "pdmvot98", "dcvot98", "pdfvot98", "turnout98")
pre_treatment1994 <- c("agrarvot94", "socialistvot94", "pibvot94", "apcdfvot94")
migrant_characteristics <- c("sh_mig_all_15_34", "sh_mig_all_fem", "sh_mig_all_high")





################################################################################
#### TABLE 1
################################################################################


### Basic controls
election_results_col1 <- function(outcome_var){
  model <- paste(paste(outcome_var, " ~ prev_mig_west + prev_mig_east +"),
                  paste(controls, collapse = "+"),
                  "+ as.factor(cod_rai)")
  
  model <- lm_robust(as.formula(model), data = community_data, clusters = cod_rai, se_type = "stata")
}

### Plus pre-migration results
election_results_col2 <- function(outcome_var){
  model <- paste(paste(outcome_var, " ~ prev_mig_west + prev_mig_east +"),
                 paste(controls, collapse = "+"), "+",
                 paste(pre_treatment1994, collapse = "+"), "+", 
                 paste(pre_treatment1998, collapse = "+"),
                 "+ as.factor(cod_rai)")
  
  model <- lm_robust(as.formula(model), data = community_data, clusters = cod_rai, se_type = "stata")
}

### Plus night-time light (baseline specification)
election_results_col3 <- function(outcome_var){
  model <- paste(paste(outcome_var, " ~ prev_mig_west + prev_mig_east +"), 
                  paste(controls, collapse = "+"), "+",
                  paste(pre_treatment1994, collapse = "+"), "+", 
                  paste(pre_treatment1998, collapse = "+"), "+",
                  paste(lights),
                  "+ as.factor(cod_rai)")
  
  model <- lm_robust(as.formula(model), data = community_data, clusters = cod_rai, se_type = "stata")
}

### Heterogeneity within the West
election_results_col4 <- function(outcome_var){
  
  model <- paste(outcome_var, "~  prev_mig_west_full + prev_mig_west_flaw + prev_mig_east +", 
                  paste(controls, collapse = "+"), "+",
                  paste(pre_treatment1994, collapse = "+"), "+", 
                  paste(pre_treatment1998, collapse = "+"), "+",
                  paste(lights),
                  "+ as.factor(cod_rai)")
  model <- lm_robust(as.formula(model), data = community_data, clusters = cod_rai, se_type = "stata")

}

election_results_col5_8 <- function(shareofvotes){
  
  model <- paste(shareofvotes, " ~  prev_mig_west + prev_mig_east +", 
                 paste(controls, collapse = "+"), "+",
                 paste(pre_treatment1994, collapse = "+"), "+", 
                 paste(pre_treatment1998, collapse = "+"), "+",
                 paste(lights),
                 "+ as.factor(cod_rai)")
  model <- lm_robust(as.formula(model), data = community_data, clusters = cod_rai, se_type = "stata")
}

```



```{r table1, echo = FALSE, fig.align= 'left'}
table1 <- huxreg("Basic controls" = election_results_col1("comvot09jul"),
                 "Plus pre- \n migration election \n results" = election_results_col2("comvot09jul"),
                 "Plus \n nighttime \n light (full \n model)" = election_results_col3("comvot09jul"),
                 "Hetero- geneity \n within \n the West" = election_results_col4("comvot09jul"),
                 
                 "Liberal\nDemocratic \n party" = election_results_col5_8("ldvot09jul"),
                 "Liberal Party" = election_results_col5_8("libvot09jul"),
                 "Demo- \n cratic Party" = election_results_col5_8("amnvot09jul"),
                 "Party \n Alliance\n Our \n Moldova" = election_results_col5_8("pdmvot09jul"),
                 
                 
                 
                 coefs = c("Prevalence of emigration to the West (percent)" = "prev_mig_west",
                           "Prevalence of emigration to the East (percent)" = "prev_mig_east",
                           "Prevalence of emigration to flawed Western democracies (percent)" = "prev_mig_west_flaw",
                           "Prevalence of emigration to full Western democracies (percent)" = "prev_mig_west_full"),
                 stars = NULL,
                 align = "r",
                 error_pos = "same", 
                 number_format = 2) %>%
  
  ## for subcaption
  insert_row("", "Share of votes for \n the Communist parties (percent)", "", "", "", "Share of votes for \n opposition parties (percent)", "", "", "", after = 0) %>%
  

  merge_cells(1, 2:5) %>%
  set_bottom_border(1, 2:5) %>%
  
  merge_cells(1, 6:9) %>%
  set_bottom_border(1, 6:9) %>%
  
    set_bottom_border(2, 0:9) %>%

  
  set_align(everywhere, everywhere, "center") %>% 
  
  set_caption("Migration Patterns and Results of the July 2009 Parliamentary Election") 

table1 <- add_footnote(table1, "Notes: The table reports OLS estimates for 848 Moldovan communities. The dependent variables are the vote 
shares of different parties in the July 2009 parliamentary election at the community level (in percent). The set of basic controls includes community-level variables capturing population size, age structure, ethnic composition, skill level, and distribution of the population, a dummy for district capitals and the cities of Chisinau and Balti, the distance to the district capital, and the next Romanian border crossing. Table A4 in the online Appendix shows the full regression results. Standard errors clustered at the district level are in parentheses. Column 4 distinguishes between full and flawed democracies within Western destinations based on the classification provided by the Economist Intelligence Unit’s index of democracy of 2006 (the index is not available for earlier years). Full Western democracies include Portugal, Greece, Spain, France, Germany, the Czech Republic, Great Britain, Ireland, the United States, Belgium, Austria, Canada, Switzerland, and the Netherlands. Flawed Western democracies include Italy, Romania, Israel, Cyprus, Bulgaria, and Poland. Moldova is also classified as a flawed democracy")

##
col_width(table1) <- c(0.3, 0.09, 0.09, 0.09, 0.09, 0.09, 0.08, 0.09, 0.08)
width(table1) <- 1
wrap(table1) <- TRUE
font_size(table1) <- 8
position(table1) <- "left"


table1
  
```



```{r table2, echo = FALSE, fig.align='left'}

table2 <- huxreg("Basic controls" = election_results_col1("comvot14nov"),
                 "Plus pre- \n migration election \n results" = election_results_col2("comvot14nov"),
                 "Plus \n nighttime \n light (full \n model)" = election_results_col3("comvot14nov"),
                 "Hetero- geneity \n within \n the West" = election_results_col4("comvot14nov"),
                 
                 "Liberal \n Demo- \n cratic \n party" = election_results_col5_8("pldmvot14nov"),
                 "Liberal Party" = election_results_col5_8("pl14nov"),
                 "Social Demo- \n cratic Party" = election_results_col5_8("psde14nov"),
                 
                 
                 coefs = c("Prevalence of emigration to the West (percent)" = "prev_mig_west",
                           "Prevalence of emigration to the East (percent)" = "prev_mig_east",
                           "Prevalence of emigration to flawed Western democracies (percent)" = "prev_mig_west_flaw",
                           "Prevalence of emigration to full Western democracies (percent)" = "prev_mig_west_full"),
                 
                 stars = NULL,
                 align = "r",
                 error_pos = "same", 
                 number_format = 2) %>%
  
  ## for subcaption
  insert_row("", "Share of votes for \n the Communist party (percent)", "", "", "", "Share of votes for \n opposition parties (percent)", "", "", after = 0) %>%

  merge_cells(1, 2:5) %>%
  set_bottom_border(1, 2:5) %>%
  
  merge_cells(1, 6:8) %>%
  set_bottom_border(1, 6:8) %>%
  
  set_align(everywhere, everywhere, "center") %>% 
    set_bottom_border(2, 0:8) %>%

  set_caption("Migration Patterns and Results of the November 2014 Parliamentary Election") 

table2 <- add_footnote(table2, "Notes: The table reports OLS estimates for 848 Moldovan communities. The dependent variables are the vote 
shares of different parties in the July 2009 parliamentary election at the community level (in percent). The set of basic controls includes community-level variables capturing population size, age structure, ethnic composition, skill level, and distribution of the population, a dummy for district capitals and the cities of Chisinau and Balti, the distance to the district capital, and the next Romanian border crossing. Table A4 in the online Appendix shows the full regression results. Standard errors clustered at the district level are in parentheses. Column 4 distinguishes between full and flawed democracies within Western destinations based on the classification provided by the Economist Intelligence Unit’s index of democracy of 2006 (the index is not available for earlier years). Full Western democracies include Portugal, Greece, Spain, France, Germany, the Czech Republic, Great Britain, Ireland, the United States, Belgium, Austria, Canada, Switzerland, and the Netherlands. Flawed Western democracies include Italy, Romania, Israel, Cyprus, Bulgaria, and Poland. Moldova is also classified as a flawed democracy")


##
col_width(table2) <- c(0.3, 0.09, 0.09, 0.09, 0.09, 0.09, 0.08, 0.09)
width(table2) <- 1
wrap(table2) <- TRUE
font_size(table2) <- 8

position(table2) <- "left"

table2

```



```{r, echo = FALSE, fig.align= 'left'}

table3 <- huxreg("Basic controls" = election_results_col1("comvot21jul"),
                 "Plus pre-\n migration election \n results" = election_results_col2("comvot21jul"),
                 "Plus \n nighttime \n light (full \n model)" = election_results_col3("comvot21jul"),
                 "Hetero- geneity \n within \n the West" = election_results_col4("comvot21jul"),
                 
                 "Party of Action and Solidarity" = election_results_col5_8("asvot21jul"),
                 "Block of Communists and Socialists" = election_results_col5_8("csvot21jul"),
                 "Șor Party" = election_results_col5_8("psvot21jul"),
                 
                 
                 coefs = c("Prevalence of emigration to the West (percent)" = "prev_mig_west",
                           "Prevalence of emigration to the East (percent)" = "prev_mig_east",
                           "Prevalence of emigration to flawed Western democracies (percent)" = "prev_mig_west_flaw",
                           "Prevalence of emigration to full Western democracies (percent)" = "prev_mig_west_full"),
                 
                 stars = NULL,
                 align = "r",
                 error_pos = "same", 
                 number_format = 2) %>%
  
  ## for subcaption
  insert_row("", "Share of votes for \n the Communist parties (percent)", "", "", "", "Share of votes for all parties \n with seats (percent)", "", "", after = 0) %>%

  merge_cells(1, 2:5) %>%
  set_bottom_border(1, 2:5) %>%
  
  merge_cells(1, 6:8) %>%
  set_bottom_border(1, 6:8) %>%
  
  set_align(everywhere, everywhere, "center") %>% 
  
  set_bottom_border(2, 0:8) %>%
  
  set_caption("Migration Patterns and Results of the November 2021 Parliamentary Election") 


table3 <- add_footnote(table3, "Notes: The table reports OLS estimates for 848 Moldovan communities. The dependent variables are the vote 
shares of different parties in the July 2009 parliamentary election at the community level (in percent). The set of basic controls includes community-level variables capturing population size, age structure, ethnic composition, skill level, and distribution of the population, a dummy for district capitals and the cities of Chisinau and Balti, the distance to the district capital, and the next Romanian border crossing. Table A4 in the online Appendix shows the full regression results. Standard errors clustered at the district level are in parentheses. Column 4 distinguishes between full and flawed democracies within Western destinations based on the classification provided by the Economist Intelligence Unit’s index of democracy of 2006 (the index is not available for earlier years). Full Western democracies include Portugal, Greece, Spain, France, Germany, the Czech Republic, Great Britain, Ireland, the United States, Belgium, Austria, Canada, Switzerland, and the Netherlands. Flawed Western democracies include Italy, Romania, Israel, Cyprus, Bulgaria, and Poland. Moldova is also classified as a flawed democracy")

##
col_width(table3) <- c(0.3, 0.09, 0.09, 0.09, 0.09, 0.09, 0.09, 0.09)
width(table3) <- 1
wrap(table3) <- TRUE
position(table3) <- "left"
font_size(table3) <- 8
table3


```




```{r , echo = FALSE}

################################################################################
#### TABLE 2
################################################################################


# load libraries
library(dplyr)
library(foreign)
library(huxtable)
library(utils)
library(estimatr)
library(broom)

# define input, output
INPUT = paste0("C:/users/soere/Documents/migration_moldova", "/01_generate_data/OUTPUT/")


# Load dataset
load(paste0(INPUT, "community_data.rda"))


# Define global variables
controls <- c("pop_1500_3000", "pop_3000_9999", "district_capital", "distance_capital", "dist_bc", "chisinau_balti", "pop_all_0_14_sh", "pop_all_15_34_sh", "pop_all_65_99_sh", "pop_highedu_sh", "pop_lowedu_sh", "ratio_high_low_edu", "eth_rus_sh", "eth_rus_sh2", "eth_ukr_sh", "eth_ukr_sh2", "eth_gag_sh", "eth_gag_sh2", "eth_bul_sh", "eth_bul_sh2", "eth_fract")
controls2 <- c("pop_1500_3000", "pop_3000_9999", "district_capital", "distance_capital", "dist_bc", "chisinau_balti", "pop_all_0_14_sh", "pop_all_15_34_sh", "pop_all_65_99_sh", "pop_highedu_sh", "pop_lowedu_sh", "ratio_high_low_edu", "eth_rus_sh", "eth_ukr_sh", "eth_gag_sh", "eth_bul_sh", "eth_fract")
lights <- "lights92_99"
pre_treatment1998 <- c("comvot98", "pdmvot98", "dcvot98", "pdfvot98", "turnout98")
pre_treatment1994 <- c("agrarvot94", "socialistvot94", "pibvot94", "apcdfvot94")
migrant_characteristics <- c("sh_mig_all_15_34", "sh_mig_all_fem", "sh_mig_all_high")





table_2 <- function(comvotyear){
  
  model1 <- paste(comvotyear, " ~  prev_mig_west + prev_mig_east +", 
                  paste(controls, collapse = "+"), "+",
                  paste(pre_treatment1994, collapse = "+"), "+", 
                  paste(pre_treatment1998, collapse = "+"), "+",
                  paste(lights),
                  "+ as.factor(cod_rai)")
  model1 <- lm_robust(as.formula(model1), data = community_data, clusters = cod_rai, se_type = "stata")

}


table2 <- huxreg("2001" = table_2("comvot01"),
                 "2005" = table_2("comvot05"),
                 "April \n 2009" = table_2("comvot09apr"),
                 "July \n 2009" = table_2("comvot09jul"),
                 "2010" = table_2("comvot10"),
                 "2014" = table_2("comvot14nov"),
                 "2021" = table_2("comvot21jul"),
                 
                 coefs = c("Prevalence of emigration to the West (percent)" = "prev_mig_west",
                           "Prevalence of emigration to the East (percent)" = "prev_mig_east"),
                 
                 stars = NULL,
                 align = "r",
                 error_pos = "same", 
                 number_format = 2) %>%
  
  ## for subcaption
  insert_row("", "Share of Communist votes in parliamentary elections \n (percent)", "", "", "", "", "", "", after = 0) %>%
  set_caption("Migration Patterns and Communist Votes over Time, 2001–2021") %>%
  set_align(everywhere, everywhere, "center") %>% 

  merge_cells(1, 2:8) %>%
  set_bottom_border(1, 2:8) %>%
  set_bottom_border(2, 1:8) 
  
  
table2 <- huxtable::add_footnote(table2, "Notes: The table reports OLS estimates for 848 Moldovan communities. The dependent variables are the vote shares of the Communist Party in the parliamentary elections between 2001 and 2010 at the community level (in percent) (columns 1–5) and a binary indicator for whether a Communist mayor was elected in the municipal elections of 1999, 2003, and 2007 (columns 6–8). The full set of controls includes community-level variables capturing population size, age structure, ethnic composition, skill level, and distribution of the population, a dummy for district capitals and the cities of Chisinau and Balti, the distance to the district capital and the next Romanian border crossing, as well as premigration election results and night-light intensity. Standard errors, clustered at the district level, are in parentheses.")

col_width(table2) <- c(0.3, 0.09, 0.09, 0.09, 0.09, 0.09, 0.08, 0.09)
width(table2) <- 1
wrap(table2) <- TRUE
font_size(table2) <- 8

position(table2) <- "left"

table2
```


```{r , echo = FALSE}

################################################################################
#### TABLE 3
################################################################################

# define input, output
INPUT = paste0("C:/users/soere/Documents/migration_moldova", "/01_generate_data/OUTPUT/")


# Load dataset
load(paste0(INPUT, "community_data.rda"))


# Define global variables
controls <- c("pop_1500_3000", "pop_3000_9999", "district_capital", "distance_capital", "dist_bc", "chisinau_balti", "pop_all_0_14_sh", "pop_all_15_34_sh", "pop_all_65_99_sh", "pop_highedu_sh", "pop_lowedu_sh", "ratio_high_low_edu", "eth_rus_sh", "eth_rus_sh2", "eth_ukr_sh", "eth_ukr_sh2", "eth_gag_sh", "eth_gag_sh2", "eth_bul_sh", "eth_bul_sh2", "eth_fract")
controls2 <- c("pop_1500_3000", "pop_3000_9999", "district_capital", "distance_capital", "dist_bc", "chisinau_balti", "pop_all_0_14_sh", "pop_all_15_34_sh", "pop_all_65_99_sh", "pop_highedu_sh", "pop_lowedu_sh", "ratio_high_low_edu", "eth_rus_sh", "eth_ukr_sh", "eth_gag_sh", "eth_bul_sh", "eth_fract")
lights <- "lights92_99"
pre_treatment1998 <- c("comvot98", "pdmvot98", "dcvot98", "pdfvot98", "turnout98")
pre_treatment1994 <- c("agrarvot94", "socialistvot94", "pibvot94", "apcdfvot94")
migrant_characteristics <- c("sh_mig_all_15_34", "sh_mig_all_fem", "sh_mig_all_high")


# estimate propensity score
community_data$comvotavg <- rowMeans(community_data[, c("comvot01", "comvot05", "comvot09apr", "comvot09jul", "comvot10")])

model1 <- paste("comvotavg ~ ",
                paste(controls2, collapse = "+"), "+",
                paste(pre_treatment1994, collapse = "+"), "+", 
                paste(pre_treatment1998, collapse = "+"), "+",
                paste(lights), 
                "+ as.factor(cod_rai)")
model1 <- lm_robust(as.formula(model1), data = community_data, clusters = cod_rai, se_type = "stata")

community_data$pscore_avg <- predict(model1, newdata = community_data)

### Communist votes
table_3 <- function(year){
  
  model <- paste(year ,"~ prev_mig_west + prev_mig_east + pscore_avg")
  model <- lm_robust(as.formula(model), data = community_data, clusters = cod_rai, se_type = "stata")

}


table3 <- huxreg("2001" = table_3("comvot01"),
                 "2005" = table_3("comvot05"),
                 "April \n 2009" = table_3("comvot09apr"),
                 "July \n 2009" = table_3("comvot09jul"),
                 "2010" = table_3("comvot10"),
                 "2014" = table_3("comvot14nov"),
                 "2021" = table_3("comvot21jul"),
                 
                 coefs = c("Prevalence of emigration to the West (percent)" = "prev_mig_west",
                           "Prevalence of emigration to the East (percent)" = "prev_mig_east",
                           "Propensity score" = "pscore_avg",
                           "Constant" = "(Intercept)"),
                 
                 stars = NULL,
                 align = "r",
                 error_pos = "same", 
                 number_format = 2) %>%
  
  ## for subcaption
  insert_row("", "Share of Communist votes in parliamentary elections \n (percent)", "", "", "", "", "", "", after = 0) %>%
  set_caption("—The Relationship of Migration Patterns and Non-migration Community Characteristics with Communist Votes over Time, 2001–2021") %>%
  set_align(everywhere, everywhere, "center") %>% 

  merge_cells(1, 2:8) %>%
  set_bottom_border(1, 2:8) %>%
  set_bottom_border(2, 1:8) 
  
  
table3<- huxtable::add_footnote(table3, "Notes: The table reports OLS estimates for 848 Moldovan communities. The dependent variables are the vote shares of the Communist Party in the parliamentary elections between 2001 and 2010 at the community level (in percent). These results correspond to the results in Table 2. The propensity score summarizes the role of all non-migration community characteristics in explaining average Communist vote shares over the period 2001–2010. To construct it, we first run a regression of the Communist vote share averaged over the period 2001–2010 on all covariates used in our baseline specification (column 3 of Table 1) except the prevalence of emigration to the West and East. We then define the propensity score as the prediction from this regression. Standard errors, clustered at the district level, are in parentheses.")

col_width(table3) <- c(0.3, 0.09, 0.09, 0.09, 0.09, 0.09, 0.08, 0.09)
width(table3) <- 1
wrap(table3) <- TRUE
font_size(table3) <- 8

position(table3) <- "left"

table3

```
